# Site settings
title: Marcos Reinan de Assis Conceição
email: marcosrdac+blog@gmail.com
description: "Testing..."
baseurl: ""
url: "marcosrdac.github.com"
twitter_username: marcosrdac
github_username:  marcosrdac

# Build settings
markdown: kramdown
permalink: pretty
