# Site settings
title: Marcos Reinan de Assis Conceição
email: marcosrdac@gmail.com
description: "Testing..."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: marcosrdac
github_username:  marcosrdac

# Build settings
markdown: kramdown
permalink: pretty
